functional:
  - Сервер возвращает корректные HTTP-статусы
  - Основной контент загружается без ошибок в консоли
  - Пользователь может авторизоваться в системе
  - Авторизованный пользователь может создавать игру
  - Пользователь может подключиться к существующей игре
  - Игра поддерживает взаимодействие двух пользователей в реальном времени
  - Пользователь может проверять решение неограниченное количество раз
  - Система корректно определяет победителя при успешном решении
  - Игра корректно завершается после выхода обоих пользователей
  - Пользователь может наблюдать за чужой игрой
  - Наблюдатель видит игровой процесс в реальном времени
  - Пользователь может просматривать профиль
  - Пользователь может изменять настройки профиля
  - Изменения в настройках сохраняются после обновления страницы
  - Пользователь может просматривать профиль другого пользователя
  - Пользователь может просматривать краткую информацию о другом игроке во всплывающем окне

non-functional:
  - Сайт адаптирован под мобильные устройства
  - Используется HTTPS
  - Сайт корректно работает в последних версиях Chrome, Firefox, Edge
  - Изображения загружаются без ошибок

implicit:
  - Интерфейс интуитивно понятен пользователю
  - Кнопки и ссылки визуально различимы и кликабельны
  - Текст читаемый
  - Поведение элементов предсказуемо
